In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
patient_file = r"C:\Users\Admin\OneDrive\Desktop\Data Science ExcelR\Assignments\Assignment 4\Patient_Data.csv"

patient_df = pd.read_csv(patient_file)
patient_df.head()

,PatientID,Name,Department,Doctor,BillAmount,ReceptionistID,CheckInTime
0,101,Alice,Cardiology,Dr. Smith,5000.0,1,2023-01-10 09:00
1,102,Bob,Neurology,Dr. John,NaN,2,2023-01-11 10:30
2,103,Charlie,Orthopedics,Dr. Lee,7500.0,1,2023-01-12 11:00
3,104,David,Cardiology,Dr. Smith,6200.0,3,2023-01-13 12:00
4,105,Eva,Dermatology,Dr. Rose,NaN,2,2023-01-14 08:45

In [3]:
billing_file = r"C:\Users\Admin\OneDrive\Desktop\Data Science ExcelR\Assignments\Assignment 4\Billing_Data.csv"

billing_df = pd.read_csv(billing_file)
billing_df.head()

   PatientID  InsuranceCovered  FinalAmount
0        101              2000         3000
1        102              1500         3500
2        103              2500         5000
3        104              3000         3200
4        105              1000         4000

In [4]:
print("Patient Dataset Information:")
patient_df.info()

Patient Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 468.0+ bytes

In [5]:
print("\nBilling Dataset Information:")
billing_df.info()

Billing Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   PatientID         5 non-null      int64
 1   InsuranceCovered  5 non-null      int64
 2   FinalAmount       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [6]:
print("Patient Dataset Shape:", patient_df.shape)
print("Billing Dataset Shape:", billing_df.shape)

Patient Dataset Shape: (6, 7)
Billing Dataset Shape: (5, 3)

In [7]:
billing_patient_df = patient_df[
    ['PatientID', 'Department', 'Doctor', 'BillAmount']
]

billing_patient_df

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

In [9]:
clean_patient_df = patient_df.copy()

clean_patient_df = clean_patient_df.drop(
    columns=['ReceptionistID', 'CheckInTime']
)

clean_patient_df

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

In [11]:
#Total Bill Amount Per Department

department_billing = (
    clean_patient_df
    .groupby('Department')['BillAmount']
    .sum()
    .reset_index()
)

department_billing

    Department  BillAmount
0   Cardiology     16200.0
1  Dermatology         0.0
2    Neurology         0.0
3  Orthopedics      7500.0

In [13]:
patient_counts = patient_df['PatientID'].value_counts()

print(patient_counts)

# Remove duplicate patients based on PatientID

unique_patient_df = clean_patient_df.drop_duplicates(
    subset='PatientID',
    keep='first'
)

unique_patient_df

print("Records before removing duplicates:", len(clean_patient_df))
print("Records after removing duplicates:", len(unique_patient_df))

PatientID
101    2
102    1
103    1
104    1
105    1
Name: count, dtype: int64
Records before removing duplicates: 6
Records after removing duplicates: 5

In [17]:
print("Missing BillAmount values:")
print(unique_patient_df['BillAmount'].isnull().sum())

mean_bill = unique_patient_df['BillAmount'].mean()

print("Mean Bill Amount:", mean_bill)

Missing BillAmount values:
0
Mean Bill Amount: 6233.333333333333

In [19]:
unique_patient_df['BillAmount'] = (
    unique_patient_df['BillAmount']
    .fillna(mean_bill)
)

unique_patient_df

print(
    "Missing BillAmount after filling:",
    unique_patient_df['BillAmount'].isnull().sum()
)

Missing BillAmount after filling: 0

C:\Users\Admin\AppData\Local\Temp\ipykernel_10764\269894470.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unique_patient_df['BillAmount'] = (

In [20]:
#Merge Billing Dataset With Patient Dataset

merged_df = pd.merge(
    unique_patient_df,
    billing_df,
    on='PatientID',
    how='left'
)

merged_df

print("Merged Dataset Shape:", merged_df.shape)

print("\nMerged Dataset:")
display(merged_df)

Merged Dataset Shape: (5, 7)

Merged Dataset:

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [21]:
print("Missing values in merged dataset:")
print(merged_df.isnull().sum())

Missing values in merged dataset:
PatientID           0
Name                0
Department          0
Doctor              0
BillAmount          0
InsuranceCovered    0
FinalAmount         0
dtype: int64

In [22]:
#Concatenate New Patients Row-Wise

new_patients = pd.DataFrame({
    'PatientID': [107, 108],
    'Name': ['George', 'Helen'],
    'Department': ['Cardiology', 'Neurology'],
    'Doctor': ['Dr. Sharma', 'Dr. Patel'],
    'BillAmount': [4500, 3800]
})

new_patients

updated_patient_df = pd.concat(
    [unique_patient_df, new_patients],
    ignore_index=True
)

updated_patient_df

print("Original Patient Records:", len(unique_patient_df))
print("New Patient Records:", len(new_patients))
print("Updated Patient Records:", len(updated_patient_df))

Original Patient Records: 5
New Patient Records: 2
Updated Patient Records: 7

In [23]:
#Concatenate New Billing Columns Column-Wise

billing_columns = billing_df[
    ['InsuranceCovered', 'FinalAmount']
]

billing_columns

patient_billing_combined = pd.concat(
    [
        unique_patient_df.reset_index(drop=True),
        billing_columns.reset_index(drop=True)
    ],
    axis=1
)

patient_billing_combined

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [24]:
#Final Cleaned Dataset

print("Final Cleaned Dataset:")
display(merged_df)

Final Cleaned Dataset:

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

In [ ]:
##The hospital patient and billing datasets were successfully loaded and analyzed using Python and Pandas.
##Relevant billing columns were selected, administrative columns were removed, duplicate patient records were identified and removed based on PatientID, and missing BillAmount values were replaced with the mean bill amount.
##The billing and patient datasets were then merged using PatientID to create a consolidated dataset.
##Additional patient records and billing information were demonstrated using row-wise and column-wise concatenation.